(lang dune 3.17)

(name TIPE)

(generate_opam_files true)

(source
 (github akSkwYX/TIPE))

(authors "SkwYX akskwyx@gmail.com")

(maintainers "SkwYX akskwyx@gmail.com")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name TIPE)
 (synopsis "My second year of prepa TIPE project")
 (description "This is a project made for my TIPE.
It's project which intend to correct french phrase.")
 (depends ocaml)
 (tags
  ("Lexing" "Parsing" "French" "Correction")))
